### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m1-evaluacion-intermedia-barbara-chaves#1]
Really cool job @barbara-chaves !!!

Here you have some tips to improve the exercise:

## HTML
- [x] Fix the meta title of the page
- [x] Put logo out of the nav tag.
- [x] Humanize text in `alt` attributes.

## CSS - structure
- [x] Move the font CSS before your main CSS

## CSS - box model
- [x] There are some weird margins, let's remove them: Remember the browser add some margins to the `<body>` element; and Any time we set an absolute or fixed position on an HTML element we should also set a left/right and a top/bottom CSS properties so it will display properly
- [x] Body has margin-top and margin. It is not correct. Why?
- [x] Your `main` element has some top padding, that's a solution to prevent the main title to disappear behind the fixed header but consider using min-height to do the trick ;)

## CSS - other
- [x] Fix h1 font-size, use devtools > inspector.
- [x] Avoid uppercase/capital on HTML texts, and `br` tag we can transform the text with CSS; this way we keep concepts separated, HTML for content, and CSS for styles
- [x] Finish the main title styles: words should jump and the typography is bolder
- [x] When using rem, remember to indicate the base size on `html` tag

## Assets
- [x] Use relative routes like `./styles/main.css`.

## Good practices
- [x] Try to improve your commit messages, better in English and using imperative
- [x] Try to use imperative for your commit messages. Ex. - > Fix central text

## Final remarks

Once you have these fixed try to finish the styles.
Start with the header and go step by step:

- add behavior styles: fix it to the window
- add structural styles: reset browser styles, center content (use whatever you feel more comfortable with: flex, text-align, margin auto...), add margin, padding...
- add cosmetic styles: color, background color...

Then repeat the same with main content.

Let me know if you have any doubts ;)

Go for it!!

**Comment by migueldelmazo** [comment]
You have a good level of programming, keep it up!!!!

**Comment by barbara-chaves** [comment]
I've finished the changes in my code, but if it's not good enough, please let me know.

**Comment by migueldelmazo** [comment]
Gracias por hacer las mejoras que os hemos pedido!!!
